services:
  - type: web
    name: countertop-configurator
    env: node
    plan: free
    branch: main
    repo: https://github.com/your-username/your-repo
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PUBLISHED_CSV_MATERIALS
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_SUBJECT
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: PUBLISHED_CSV_LABOR
        sync: false
